name: supachat
description: Demo chat app using supabase and flutter
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase: ^0.2.7
  adaptive_theme: ^2.2.0
  provider: ^6.0.0
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.6
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  fonts:
    - family: George
      fonts:
        - asset: fonts/George.ttf
